[package]
name = "day_6"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
roots = "0.0.8"
library = { git="https://github.com/ThomasDavidson/Advent-of-Code-Library.git", tag = "v0.2.0"}
