[package]
name = "day_14"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
library = { git="https://github.com/ThomasDavidson/Advent-of-Code-Library.git", tag = "v0.2.0"}
